name: CI
on:
  - push
  - pull_request
run_awesome_lint:
  runs-on: ubuntu-latest
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run awesome-lint
      run: npx awesome-lint
